name: Run SonarCloud analysis

on:
    workflow_call:
        inputs:
            project-key:
                required: true
                type: string
        secrets:
            SONAR_TOKEN:
                required: true

jobs:

    sonarcloud:
        runs-on: ubuntu-latest
        steps:
            -   name: Checkout
                uses: actions/checkout@v3
                with:
                    fetch-depth: 0
            -   name: Download coverage
                uses: actions/download-artifact@v2
                with:
                    name: coverage
            -   name: Fix code coverage paths
                run: |
                    sed -i 's@'$GITHUB_WORKSPACE'@/github/workspace@g' coverage.clover.xml
                    sed -i 's@'$GITHUB_WORKSPACE'@/github/workspace@g' log.junit.xml
            -   name: SonarCloud Scan
                uses: sonarsource/sonarcloud-github-action@v1.8
                env:
                    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                    SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
                with:
                    args: >
                        -Dsonar.organization=dontdrinkandroot
                        -Dsonar.projectKey=${{ inputs.project-key }}
                        -Dsonar.exclusions=vendor/**,coverage.clover.xml,log.junit.xml
                        -Dsonar.sourceEncoding=UTF-8
                        -Dsonar.php.tests.reportPaths=log.junit.xml
                        -Dsonar.php.coverage.reportPaths=coverage.clover.xml
                        -Dsonar.sources=src
                        -Dsonar.tests=tests
